%% ECE 253 Homework 4 
% _*Shivani Bhakta*_
% A13832428

%% Problem 1 2D Sampling and Aliasing
%% _Part(a)_
clear; close all; clc; 
[x y] = meshgrid(0:256,0:256); 
figure, subplot(1,2,1), imshow(x, [0, 255])
subplot(1,2,2), imshow(y, [0, 255]), title('x, y ')
%%
%
% * We are given the sampling period T =  1, thus the sampling frequency 
% $F_s$ = 1. 
% * x and y are the spatial coordinates of the original image given by the
% mesh grid in matlab 
% * u and v are the spatial frequency coordinates of the Fourier transform 
% of the image. 

%% 
z1 = cos ( 2 * pi * 1/32 .* x - 2 * pi * 1/128 .* y); 
figure, imshow(z1), title('z1 matrix/image');

%%
%
% Spatial Frequencies for z1. 
%
% * In x-direction = 1/32 
% * In y-direction = 1/128 
% 
% Image can be reconstructed exactly from it's samples if 
% Cutoff freq ≤ 1/2 sampling freq $F_s$
%
% * If equality holds, then the sampling is at the Nyquist rate
% * If Δx and Δy are smaller than required, the image is called oversampled
% * If they are larger than required, the image is undersampled
%
% In terms of spatial frequency and the sampling frequency, 
% 
% * 2 * 1/32 = 1/16 < $F_s$ =  1 ==> oversampled in x-direction 
% * 2 * 1/128 = 1/64 < $F_s$ =  1 ==> oversampled in y-direction
%

%% 
z2 = cos ( 2 * pi * 1/4 .* x - 2 * pi * 7/8 .* y); 
figure, imshow(z2), truesize, title('z2 matrix/image');

%%
%
% Spatial Frequencies for z2. 
%
% * In x-direction  = 1/4 
% * In y-direction  = 7/8 
% 
% In terms of spatial frequency and the sampling frequency, 
% 
% * 2 * $F_{xc}$ = 1/2 < $F_s$ =  1 ==> oversamppled in x-direction  
% * 2 * $F_{yc}$ = 7/4 > $F_s$ =  1 ==> undersampled  in y-direction 
%

%%
z3 = cos ( 2 * pi * 1/2 .* x - 2 * pi * 1/2 .* y); 
figure, imshow(z3), title('z3 matrix/image'); 

%%
%
% Spatial Frequencies for z3. 
%
% * In x-direction = 1/2 
% * In y-direction = 1/2 
% 
% In terms of spatial frequency and the sampling frequency,  
% 
% * 2 * $F_{xc}$ = 1 = $F_s$ =  1 ==> critically sampled in x-direction  or 
% sampling is at the Nyquist rate
% * 2 * $F_{yc}$ = 1 > $F_s$ =  1 ==> critically sampled in y-direction or 
% sampling is at the Nyquist rate
%
% 
%% _Part(b)_
%%
% Since Cosine function is periodic with period 2$\pi$ . 
% we can use any frequencies which is generated by adding any multiple of 
% 2 $\pi$ to each of the xy frequency components in z1 to obtain a 
% identical sampled function to that of the sampled function z1. 
% Therefore let us consider a = $F_{xc}$ + 2$\pi$ and b = $F_{yc}$ + 
% 2$\pi$, taking the 2$\pi$ in common we get a = 33/32 b = 129/128  
% Any a = 1/32 + k 2$\pi$  where k $\in$ z, will give us the identical
% sampled function.
%
% However, we have to note that the we want the sampled function to be
% aliased, this means we have to consider the inequality a>1/2 and b>1/2 
%
z4 = cos ( 2 * pi * 33/32 .* x - 2 * pi * 129/128 .* y);
figure, imshow(z4), title('z3 matrix/image'); 
%%
% In the figure above it came be seen that z4 produces the same image as
% sampled in z1. 


